// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsLkM-wXETn7xoXcScjoBlvl9mlUYwro',
    appId: '1:985662232842:web:899c45462e54bd95d782f3',
    messagingSenderId: '985662232842',
    projectId: 'lightbulb-703a1',
    authDomain: 'lightbulb-703a1.firebaseapp.com',
    storageBucket: 'lightbulb-703a1.appspot.com',
    measurementId: 'G-6RFP9F84M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2yaBVcGrekwPPPrzFAAx-KHe6e1o-x5o',
    appId: '1:985662232842:android:e5697e6d8fad6d86d782f3',
    messagingSenderId: '985662232842',
    projectId: 'lightbulb-703a1',
    storageBucket: 'lightbulb-703a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABSvizLT6Tl-s5WVWxry4U5fXdg4A2jlI',
    appId: '1:985662232842:ios:725d34dc0a0da0afd782f3',
    messagingSenderId: '985662232842',
    projectId: 'lightbulb-703a1',
    storageBucket: 'lightbulb-703a1.appspot.com',
    androidClientId: '985662232842-0tlvsirrrhige0d5el7ln3d1vc2v96ag.apps.googleusercontent.com',
    iosClientId: '985662232842-pillfccrce1eqlpaim98iljf1u3tbs0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightbulb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABSvizLT6Tl-s5WVWxry4U5fXdg4A2jlI',
    appId: '1:985662232842:ios:725d34dc0a0da0afd782f3',
    messagingSenderId: '985662232842',
    projectId: 'lightbulb-703a1',
    storageBucket: 'lightbulb-703a1.appspot.com',
    androidClientId: '985662232842-0tlvsirrrhige0d5el7ln3d1vc2v96ag.apps.googleusercontent.com',
    iosClientId: '985662232842-pillfccrce1eqlpaim98iljf1u3tbs0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.lightbulb',
  );
}
